require "open-uri"
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Favorite.destroy_all
puts "favoris destroy ok"

Creation.destroy_all
puts "creation destroy ok"

puts "debut seed"

foulard_chouchou = Creation.create!(name: 'Chouchou foulard', longueur: 50, largeur: 35, tissue_type: "", video_link: "src='https://www.youtube.com/embed/5y9jsSfDNYs' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'", patron_link: "pdf/patrons/chouchou_foulard_patron.pdf", notice_pdf: "pdf/notices/chouchou_foulard_notice.pdf", tagline: "Les chouchous foulards, c’est notre astuce pour une coiffure toujours chic.", description:"Je vous avoue un secret. La plupart du temps, si vous me voyez coiffée d’un chouchou, c’est que je n’ai pas eu l’énergie de me coiffer. Je ramasse mes cheveux d’un côté, je noue mon chouchou et me voilà parée d’une belle coiffure vite fait, bien fait ! C’est une couture très facile et rapide à réaliser. Je vous recommande ce projet si vous débutez la couture. Ou pour coudre avec les enfants par exemple.
", instruction: "Je vous propose deux versions de nœud : un nœud court et un nœud long, de type foulard. Pour coudre un foulchie, comme on l’entend parfois.", time: 1)
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373341/FabricsApp/Chouchou_foulard/chouchou_foulard_photo_principale_huc1eq.jpg')
foulard_chouchou.photos.attach(io: file1, filename: 'foulard_chouchou.jpg', content_type: 'image/jpg')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373342/FabricsApp/Chouchou_foulard/chouchou_foulard_photo_2_fmvzfx.jpg')
foulard_chouchou.photos.attach(io: file2, filename: 'foulard_chouchou2.jpg', content_type: 'image/jpg')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373342/FabricsApp/Chouchou_foulard/chouchou_foulard_photo_3_xiiao8.jpg')
foulard_chouchou.photos.attach(io: file3, filename: 'foulard_chouchou3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373342/FabricsApp/Chouchou_foulard/chouchou_foulard_photo_3bis_ddtmra.jpg')
foulard_chouchou.photos.attach(io: file4, filename: 'foulard_chouchou4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373342/FabricsApp/Chouchou_foulard/chouchou_foulard_photo_4_bipiry.jpg')
foulard_chouchou.photos.attach(io: file5, filename: 'foulard_chouchou5.jpg', content_type: 'image/jpg')
notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_1_cdo4cn.png')
foulard_chouchou.photos.attach(io: notice1, filename: 'foulard_chouchou_notice1.png', content_type: 'image/png')
notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711685/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_2_ye3eyd.png')
foulard_chouchou.photos.attach(io: notice2, filename: 'foulard_chouchou_notice2.png', content_type: 'image/png')
notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_3_nskrdr.png')
foulard_chouchou.photos.attach(io: notice3, filename: 'foulard_chouchou_notice3.png', content_type: 'image/png')
notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_4_jgw9j6.png')
foulard_chouchou.photos.attach(io: notice4, filename: 'foulard_chouchou_notice4.png', content_type: 'image/png')
notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_5_ck2wjw.png')
foulard_chouchou.photos.attach(io: notice5, filename: 'foulard_chouchou_notice5.png', content_type: 'image/png')
notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_6_xmeact.png')
foulard_chouchou.photos.attach(io: notice6, filename: 'foulard_chouchou_notice6.png', content_type: 'image/png')
notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655711686/FabricsApp/Chouchou_foulard/chouchou_foulard_notice_Page_7_iuyxwm.png')
foulard_chouchou.photos.attach(io: notice7, filename: 'foulard_chouchou_notice7.png', content_type: 'image/png')

puts "#{Creation.count} creations created"

doudou_lapin = Creation.create!(name: 'Doudou lapin', longueur: 60, largeur: 40, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/doudou_lapin_patron.pdf", notice_pdf: "pdf/notices/doudou_lapin_notice.pdf", tagline: "Le lapin le plus mignon et le plus doux depuis que les doudous existent !", description:"Les doudous font partie des premiers jouets et procurent un sentiment rassurant de sécurité. Notre doudou lapin peut être cousu de manière typique en tissu peluche, mais aussi en polaire ou en tissu nid d’abeille.", instruction: "Avec un patch ou une broderie, le doudou devient un cadeau individuel et très spécial.", time: 3)
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373483/FabricsApp/Doudou_lapin/doudou_lapin_photo_1_m3oxfv.webp')
doudou_lapin.photos.attach(io: file1, filename: 'doudou_lapin.webp', content_type: 'image/webp')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373483/FabricsApp/Doudou_lapin/doudou_lapin_photo_2_kmylle.webp')
doudou_lapin.photos.attach(io: file2, filename: 'doudou_lapin2.webp', content_type: 'image/webp')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373483/FabricsApp/Doudou_lapin/doudou_lapin_photo_3_vzyxcu.webp')
doudou_lapin.photos.attach(io: file3, filename: 'doudou_lapin3.webp', content_type: 'image/webp')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373483/FabricsApp/Doudou_lapin/doudou_lapin_photo_4_lpfbwi.webp')
doudou_lapin.photos.attach(io: file4, filename: 'doudou_lapin4.webp', content_type: 'image/webp')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373483/FabricsApp/Doudou_lapin/doudou_lapin_photo_5_ur50mp.jpg')
doudou_lapin.photos.attach(io: file5, filename: 'doudou_lapin5.webp', content_type: 'image/webp')
notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712493/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_01_vtgbi3.png')
doudou_lapin.photos.attach(io: notice1, filename: 'doudou_lapin_notice1.png', content_type: 'image/png')
notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712493/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_03_qtheej.png')
doudou_lapin.photos.attach(io: notice2, filename: 'doudou_lapin_notice2.png', content_type: 'image/png')
notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712494/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_04_hld3np.png')
doudou_lapin.photos.attach(io: notice3, filename: 'doudou_lapin_notice3.png', content_type: 'image/png')
notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712495/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_05_c6dmjv.png')
doudou_lapin.photos.attach(io: notice4, filename: 'doudou_lapin_notice4.png', content_type: 'image/png')
notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712495/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_06_a1ogv3.png')
doudou_lapin.photos.attach(io: notice5, filename: 'doudou_lapin_notice5.png', content_type: 'image/png')
notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712495/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_07_orxkjt.png')
doudou_lapin.photos.attach(io: notice6, filename: 'doudou_lapin_notice6.png', content_type: 'image/png')
notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712494/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_08_p6lkpm.png')
doudou_lapin.photos.attach(io: notice7, filename: 'doudou_lapin_notice7.png', content_type: 'image/png')
notice8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712496/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_09_rhgjt4.png')
doudou_lapin.photos.attach(io: notice8, filename: 'doudou_lapin_notice8.png', content_type: 'image/png')
notice9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712495/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_10_e63l82.png')
doudou_lapin.photos.attach(io: notice9, filename: 'doudou_lapin_notice9.png', content_type: 'image/png')
notice10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712495/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_11_lnczlj.png')
doudou_lapin.photos.attach(io: notice10, filename: 'doudou_lapin_notice10.png', content_type: 'image/png')
notice11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712496/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_12_zntn8c.png')
doudou_lapin.photos.attach(io: notice11, filename: 'doudou_lapin_notice11.png', content_type: 'image/png')
notice12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712499/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_13_o8ak1r.png')
doudou_lapin.photos.attach(io: notice12, filename: 'doudou_lapin_notice12.png', content_type: 'image/png')
notice13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712496/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_14_ut1jra.png')
doudou_lapin.photos.attach(io: notice13, filename: 'doudou_lapin_notice13.png', content_type: 'image/png')
notice14 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712496/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_15_aesdjc.png')
doudou_lapin.photos.attach(io: notice14, filename: 'doudou_lapin_notice14.png', content_type: 'image/png')
notice15 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712498/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_16_iyh7ad.png')
doudou_lapin.photos.attach(io: notice15, filename: 'doudou_lapin_notice15.png', content_type: 'image/png')
notice16 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712496/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_17_qpb9at.png')
doudou_lapin.photos.attach(io: notice16, filename: 'doudou_lapin_notice16.png', content_type: 'image/png')
notice17 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712497/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_18_p84huq.png')
doudou_lapin.photos.attach(io: notice17, filename: 'doudou_lapin_notice17.png', content_type: 'image/png')
notice18 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712497/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_19_u9ibk9.png')
doudou_lapin.photos.attach(io: notice18, filename: 'doudou_lapin_notice18.png', content_type: 'image/png')
notice19 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712499/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_20_prlmgg.png')
doudou_lapin.photos.attach(io: notice19, filename: 'doudou_lapin_notice19.png', content_type: 'image/png')
notice20 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712497/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_21_sp0lgt.png')
doudou_lapin.photos.attach(io: notice20, filename: 'doudou_lapin_notice20.png', content_type: 'image/png')
notice21 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712501/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_22_zsjv9l.png')
doudou_lapin.photos.attach(io: notice21, filename: 'doudou_lapin_notice21.png', content_type: 'image/png')
notice22 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712498/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_23_eing0i.png')
doudou_lapin.photos.attach(io: notice22, filename: 'doudou_lapin_notice22.png', content_type: 'image/png')
notice23 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712497/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_24_hzjvjy.png')
doudou_lapin.photos.attach(io: notice23, filename: 'doudou_lapin_notice23.png', content_type: 'image/png')
notice24 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712499/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_25_ajcmqv.png')
doudou_lapin.photos.attach(io: notice24, filename: 'doudou_lapin_notice24.png', content_type: 'image/png')
notice25 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655712498/FabricsApp/Doudou_lapin/doudou_lapin_notice_Page_26_mulhv3.png')
doudou_lapin.photos.attach(io: notice25, filename: 'doudou_lapin_notice25.png', content_type: 'image/png')

puts "#{Creation.count} creations created"

ballon = Creation.create!(name: 'Ballon', longueur: 90, largeur: 63, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/ballon_patron.pdf", notice_pdf: "pdf/notices/ballon_notice.pdf", tagline: "Ce ballon devient un objet ludique unique et résistant ", description:"La housse est lavable, réutilisable à l’infini et constitue également une excellente idée de cadeau pour l’anniversaire d’un enfant. Les tissus non extensibles tels que la popeline, le tissu fanion, le lin ou la cretonne conviennent pour ce projet de couture. Les tissus en coton enduit ont en outre l’avantage de permettre à la balle de résister à de nombreuses flaques d’eau.", instruction: "Ce ebook gratuit offre
d’innombrables possibilités et convient également aux débutants en couture.", time: 2)
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373415/FabricsApp/Ballon/ballon_photo_1_ixsd4a.webp')
ballon.photos.attach(io: file1, filename: 'ballon.webp', content_type: 'image/webp')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373415/FabricsApp/Ballon/ballon_photo_2_u8eqgw.jpg')
ballon.photos.attach(io: file2, filename: 'ballon2.jpg', content_type: 'image/jpg')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655730605/FabricsApp/Ballon/ballon_photo_3_t1mf1u.jpg')
ballon.photos.attach(io: file3, filename: 'ballon3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655730604/FabricsApp/Ballon/ballon_photo_4_bwm4bu.jpg')
ballon.photos.attach(io: file4, filename: 'ballon4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655730604/FabricsApp/Ballon/ballon_photo_5_vxbswt.jpg')
ballon.photos.attach(io: file5, filename: 'ballon5.jpg', content_type: 'image/jpg')
notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_01_a4li63.png')
ballon.photos.attach(io: notice1, filename: 'ballon_notice1.jpg', content_type: 'image/jpg')
notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_03_wec4vi.png')
ballon.photos.attach(io: notice2, filename: 'ballon_notice2.jpg', content_type: 'image/jpg')
notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716898/FabricsApp/Ballon/ballon_notice_Page_04_glb5if.png')
ballon.photos.attach(io: notice3, filename: 'ballon_notice3.png', content_type: 'image/png')
notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716901/FabricsApp/Ballon/ballon_notice_Page_05_rszyqf.png')
ballon.photos.attach(io: notice4, filename: 'ballon_notice4.png', content_type: 'image/png')
notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_06_crqyuk.png')
ballon.photos.attach(io: notice5, filename: 'ballon_notice5.png', content_type: 'image/png')
notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716900/FabricsApp/Ballon/ballon_notice_Page_07_vvboum.png')
ballon.photos.attach(io: notice6, filename: 'ballon_notice6.png', content_type: 'image/png')
notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716901/FabricsApp/Ballon/ballon_notice_Page_08_ciecpq.png')
ballon.photos.attach(io: notice7, filename: 'ballon_notice7.png', content_type: 'image/png')
notice8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_09_v1mbwc.png')
ballon.photos.attach(io: notice8, filename: 'ballon_notice8.png', content_type: 'image/png')
notice9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716900/FabricsApp/Ballon/ballon_notice_Page_10_mombcr.png')
ballon.photos.attach(io: notice9, filename: 'ballon_notice9.png', content_type: 'image/png')
notice10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716900/FabricsApp/Ballon/ballon_notice_Page_11_sfm3op.png')
ballon.photos.attach(io: notice10, filename: 'ballon_notice10.png', content_type: 'image/png')
notice11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_12_pyl5im.png')
ballon.photos.attach(io: notice11, filename: 'ballon_notice11.png', content_type: 'image/png')
notice12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716900/FabricsApp/Ballon/ballon_notice_Page_13_kntqvk.png')
ballon.photos.attach(io: notice12, filename: 'ballon_notice12.png', content_type: 'image/png')
notice13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655716899/FabricsApp/Ballon/ballon_notice_Page_14_qodza6.png')
ballon.photos.attach(io: notice13, filename: 'ballon_notice13.png', content_type: 'image/png')

puts "#{Creation.count} creations created"

sac_a_dos_enfant = Creation.create!(name: 'Sac à dos enfant', longueur: 240, largeur: 168, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/sac_a_dos_enfant_patron.pdf", notice_pdf: "pdf/notices/sac_a_dos_enfant_notice.pdf", tagline: "Notre sac à dos pour enfants ALEX dans le style messager tendance !", description:"ce joli sac à dos a des bretelles rembourrées, un porte-bouteille et une petite poche intérieure avec velcro. Un excellent compagnon pour le
Maternelle ou pour les premières aventures et excursions.", instruction: "Tissus conseillés : toile, velours côtelé, cretonne, popeline, coton enduit, simili cuir, liège, ciré", time: 5)
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373537/FabricsApp/Sac_a_dos_enfant/Sac_a_dos_enfant_photo_1_a6rxqa.webp')
sac_a_dos_enfant.photos.attach(io: file1, filename: 'sac_a_dos_enfant.webp', content_type: 'image/webp')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373537/FabricsApp/Sac_a_dos_enfant/Sac_a_dos_enfant_photo_2_usn4sr.webp')
sac_a_dos_enfant.photos.attach(io: file2, filename: 'sac_a_dos_enfant2.webp', content_type: 'image/webp')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373537/FabricsApp/Sac_a_dos_enfant/Sac_a_dos_enfant_photo_3_zqvlxd.jpg')
sac_a_dos_enfant.photos.attach(io: file3, filename: 'sac_a_dos_enfant3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655373537/FabricsApp/Sac_a_dos_enfant/Sac_a_dos_enfant_photo_4_liqqom.jpg')
sac_a_dos_enfant.photos.attach(io: file4, filename: 'sac_a_dos_enfant4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655730418/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_photo_5_c8wtsy.jpg')
sac_a_dos_enfant.photos.attach(io: file5, filename: 'sac_a_dos_enfant5.jpg', content_type: 'image/jpg')
notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713666/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_01_lxfx48.png')
sac_a_dos_enfant.photos.attach(io: notice1, filename: 'sac_a_dos_enfant_notice1.png', content_type: 'image/png')
notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713666/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_03_izyhab.png')
sac_a_dos_enfant.photos.attach(io: notice2, filename: 'sac_a_dos_enfant_notice2.png', content_type: 'image/png')
notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713666/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_04_tw5y6y.png')
sac_a_dos_enfant.photos.attach(io: notice3, filename: 'sac_a_dos_enfant_notice3.png', content_type: 'image/png')
notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713666/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_05_j9gyxg.png')
sac_a_dos_enfant.photos.attach(io: notice4, filename: 'sac_a_dos_enfant_notice4.png', content_type: 'image/png')
notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713666/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_06_dn1wey.png')
sac_a_dos_enfant.photos.attach(io: notice5, filename: 'sac_a_dos_enfant_notice5.png', content_type: 'image/png')
notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_07_lyu43a.png')
sac_a_dos_enfant.photos.attach(io: notice6, filename: 'sac_a_dos_enfant_notice6.png', content_type: 'image/png')
notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713667/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_08_ezlmag.png')
sac_a_dos_enfant.photos.attach(io: notice7, filename: 'sac_a_dos_enfant_notice7.png', content_type: 'image/png')
notice8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713667/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_09_eabq1w.png')
sac_a_dos_enfant.photos.attach(io: notice8, filename: 'sac_a_dos_enfant_notice8.png', content_type: 'image/png')
notice9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713667/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_10_s2bom0.png')
sac_a_dos_enfant.photos.attach(io: notice9, filename: 'sac_a_dos_enfant_notice9.png', content_type: 'image/png')
notice10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713667/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_11_kibtvs.png')
sac_a_dos_enfant.photos.attach(io: notice10, filename: 'sac_a_dos_enfant_notice10.png', content_type: 'image/png')
notice11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_12_kgk4x7.png')
sac_a_dos_enfant.photos.attach(io: notice11, filename: 'sac_a_dos_enfant_notice11.png', content_type: 'image/png')
notice12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713667/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_13_ud8esw.png')
sac_a_dos_enfant.photos.attach(io: notice12, filename: 'sac_a_dos_enfant_notice12.png', content_type: 'image/png')
notice13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_14_zl4jd3.png')
sac_a_dos_enfant.photos.attach(io: notice13, filename: 'sac_a_dos_enfant_notice13.png', content_type: 'image/png')
notice14 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_15_owoyqp.png')
sac_a_dos_enfant.photos.attach(io: notice14, filename: 'sac_a_dos_enfant_notice14.png', content_type: 'image/png')
notice15 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_16_s8tday.png')
sac_a_dos_enfant.photos.attach(io: notice15, filename: 'sac_a_dos_enfant_notice15.png', content_type: 'image/png')
notice16 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713668/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_17_sk6mqh.png')
sac_a_dos_enfant.photos.attach(io: notice16, filename: 'sac_a_dos_enfant_notice16.png', content_type: 'image/png')
notice17 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_18_lo67ya.png')
sac_a_dos_enfant.photos.attach(io: notice17, filename: 'sac_a_dos_enfant_notice17.png', content_type: 'image/png')
notice18 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_19_mkn6v8.png')
sac_a_dos_enfant.photos.attach(io: notice18, filename: 'sac_a_dos_enfant_notice18.png', content_type: 'image/png')
notice19 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_20_lo0b5l.png')
sac_a_dos_enfant.photos.attach(io: notice19, filename: 'sac_a_dos_enfant_notice19.png', content_type: 'image/png')
notice20 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_21_mebccs.png')
sac_a_dos_enfant.photos.attach(io: notice20, filename: 'sac_a_dos_enfant_notice20.png', content_type: 'image/png')
notice21 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_22_yakeq1.png')
sac_a_dos_enfant.photos.attach(io: notice21, filename: 'sac_a_dos_enfant_notice21.png', content_type: 'image/png')
notice22 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713669/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_23_ynrbep.png')
sac_a_dos_enfant.photos.attach(io: notice22, filename: 'sac_a_dos_enfant_notice22.png', content_type: 'image/png')
notice23 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_24_yrfnai.png')
sac_a_dos_enfant.photos.attach(io: notice23, filename: 'sac_a_dos_enfant_notice23.png', content_type: 'image/png')
notice24 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_25_zcnefn.png')
sac_a_dos_enfant.photos.attach(io: notice24, filename: 'sac_a_dos_enfant_notice24.png', content_type: 'image/png')
notice25 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_26_xwsty4.png')
sac_a_dos_enfant.photos.attach(io: notice25, filename: 'sac_a_dos_enfant_notice25.png', content_type: 'image/png')
notice26 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_27_wsxasy.png')
sac_a_dos_enfant.photos.attach(io: notice26, filename: 'sac_a_dos_enfant_notice26.png', content_type: 'image/png')
notice27 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_28_xsjh0w.png')
sac_a_dos_enfant.photos.attach(io: notice27, filename: 'sac_a_dos_enfant_notice27.png', content_type: 'image/png')
notice28 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713670/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_29_ud2h1v.png')
sac_a_dos_enfant.photos.attach(io: notice28, filename: 'sac_a_dos_enfant_notice28.png', content_type: 'image/png')
notice29 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_30_tehtxn.png')
sac_a_dos_enfant.photos.attach(io: notice29, filename: 'sac_a_dos_enfant_notice29.png', content_type: 'image/png')
notice30 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_31_wkzlz6.png')
sac_a_dos_enfant.photos.attach(io: notice30, filename: 'sac_a_dos_enfant_notice30.png', content_type: 'image/png')
notice31 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_32_nleejn.png')
sac_a_dos_enfant.photos.attach(io: notice31, filename: 'sac_a_dos_enfant_notice31.png', content_type: 'image/png')
notice32 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_33_n3qywj.png')
sac_a_dos_enfant.photos.attach(io: notice32, filename: 'sac_a_dos_enfant_notice32.png', content_type: 'image/png')
notice33 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_34_gns88x.png')
sac_a_dos_enfant.photos.attach(io: notice33, filename: 'sac_a_dos_enfant_notice33.png', content_type: 'image/png')
notice34 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_35_bmmjuk.png')
sac_a_dos_enfant.photos.attach(io: notice34, filename: 'sac_a_dos_enfant_notice34.png', content_type: 'image/png')
notice35 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655713671/FabricsApp/Sac_a_dos_enfant/sac_a_dos_enfant_notice_Page_36_gnnton.png')
sac_a_dos_enfant.photos.attach(io: notice35, filename: 'sac_a_dos_enfant_notice35.png', content_type: 'image/png')

puts "#{Creation.count} creations created"

couronne = Creation.create!(name: 'Couronne', longueur: 50, largeur: 40, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/couronne_vague_sirene_patron.pdf", notice_pdf: "pdf/notices/couronne_vague_sirene_notice.pdf", tagline: "Une vraie sirène a naturellement une couronne dont les pointes sont ornées de jolies perles de mer.", description:"Cousu à partir de tissus non extensibles comme le tissu en coton et renforcé par un insert polaire, vous vous cousez une grande couronne avec ce livre gratuit, qui sera certainement porté avec fierté.", instruction: "Étape par étape, ces instructions conviennent également aux débutants en couture.", time: 2)
  file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726983/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_o8eyrm.jpg')
  couronne.photos.attach(io: file1, filename: 'couronne.jpg', content_type: 'image/jpg')
  file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726983/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene2_akz4kt.jpg')
  couronne.photos.attach(io: file2, filename: 'couronne2.jpg', content_type: 'image/jpg')
  file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731019/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene3_fbqmt9.jpg')
  couronne.photos.attach(io: file3, filename: 'couronne3.jpg', content_type: 'image/jpg')
  file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731019/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene4_pdjbpp.jpg')
  couronne.photos.attach(io: file4, filename: 'couronne4.jpg', content_type: 'image/jpg')
  file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731018/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene5_f9mh8f.webp')
  couronne.photos.attach(io: file5, filename: 'couronne5.jpg', content_type: 'image/jpg')
  notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_01_amprqt.png')
  couronne.photos.attach(io: notice1, filename: 'couronne_notice1.png', content_type: 'image/png')
  notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_02_fj9oaz.png')
  couronne.photos.attach(io: notice2, filename: 'couronne_notice2.png', content_type: 'image/png')
  notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_03_wn2mo5.png')
  couronne.photos.attach(io: notice3, filename: 'couronne_notice3.png', content_type: 'image/png')
  notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_04_cts1yz.png')
  couronne.photos.attach(io: notice4, filename: 'couronne_notice4.png', content_type: 'image/png')
  notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_05_tlroot.png')
  couronne.photos.attach(io: notice5, filename: 'couronne_notice5.png', content_type: 'image/png')
  notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726976/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_06_w2gite.png')
  couronne.photos.attach(io: notice6, filename: 'couronne_notice6.png', content_type: 'image/png')
  notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726977/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_07_hn8mnj.png')
  couronne.photos.attach(io: notice7, filename: 'couronne_notice7.png', content_type: 'image/png')
  notice8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726977/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_08_ul3c3j.png')
  couronne.photos.attach(io: notice8, filename: 'couronne_notice8.png', content_type: 'image/png')
  notice9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726977/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_09_gzocsv.png')
  couronne.photos.attach(io: notice9, filename: 'couronne_notice9.png', content_type: 'image/png')
  notice10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726978/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_10_martc8.png')
  couronne.photos.attach(io: notice10, filename: 'couronne_notice10.png', content_type: 'image/png')
  notice11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655726977/FabricsApp/Couronne_vague-sir%C3%A8ne/couronne_vague_sirene_notice_Page_11_jygsfc.png')
  couronne.photos.attach(io: notice11, filename: 'couronne_notice11.png', content_type: 'image/png')

  puts "#{Creation.count} creations created"

  serviette_turban = Creation.create!(name: 'Serviette turban Nala', longueur: 80, largeur: 80, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/serviette_turban_patron.pdf", notice_pdf: "pdf/notices/serviette_turban_notice.pdf", tagline: "Notre turban serviette pratique NALA repose si merveilleusement sur la tête !", description:"Cousu en tissus éponge pour une absorbtion optimisée, idéal également pour l'application de masques capillaires et soins.", instruction: "Étape par étape, ces instructions conviennent également aux débutants en couture.", time: 2)
  file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728826/FabricsApp/Serviette%20turban%20Nala/serviette_turban1_njmine.webp')
  serviette_turban.photos.attach(io: file1, filename: 'serviette_turban.webp', content_type: 'image/webp')
  file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728826/FabricsApp/Serviette%20turban%20Nala/serviette_turban2_rdonva.webp')
  serviette_turban.photos.attach(io: file2, filename: 'serviette_turban2.webp', content_type: 'image/webp')
  file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731237/FabricsApp/Serviette%20turban%20Nala/serviette_turban3_es8rbz.jpg')
  serviette_turban.photos.attach(io: file3, filename: 'serviette_turban3.jpg', content_type: 'image/jpg')
  file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731237/FabricsApp/Serviette%20turban%20Nala/serviette_turban4_x8fu6n.webp')
  serviette_turban.photos.attach(io: file4, filename: 'serviette_turban4.webp', content_type: 'image/webp')
  file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731237/FabricsApp/Serviette%20turban%20Nala/serviette_turban5_mrwdn1.jpg')
  serviette_turban.photos.attach(io: file5, filename: 'serviette_turban5.jpg', content_type: 'image/jpg')
  notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_1_uadmst.png')
  serviette_turban.photos.attach(io: notice1, filename: 'serviette_turban_notice1.png', content_type: 'image/png')
  notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_2_odh8yk.png')
  serviette_turban.photos.attach(io: notice2, filename: 'serviette_turban_notice2.png', content_type: 'image/png')
  notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_3_ofvpmq.png')
  serviette_turban.photos.attach(io: notice3, filename: 'serviette_turban_notice3.png', content_type: 'image/png')
  notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_4_kty4w6.png')
  serviette_turban.photos.attach(io: notice4, filename: 'serviette_turban_notice4.png', content_type: 'image/png')
  notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_5_zrb9ut.png')
  serviette_turban.photos.attach(io: notice5, filename: 'serviette_turban_notice5.png', content_type: 'image/png')
  notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655728614/FabricsApp/Serviette%20turban%20Nala/serviette_turban_notice_Page_6_aokyep.png')
  serviette_turban.photos.attach(io: notice6, filename: 'serviette_turban_notice6.png', content_type: 'image/png')

  puts "#{Creation.count} creations created"

  sac_a_tartes = Creation.create!(name: 'Sac à tartes', longueur: 50, largeur: 50, tissue_type: "", video_link: "test link", patron_link: "pdf/patrons/sac_a_tartes_patron.jfif", notice_pdf: "pdf/notices/sac_a_tartes_notice.pdf.pdf", tagline: "Un petit repas en famille ou entre amis, vous apportez un plat ou le dessert. Voici un sac original qui vous permettra de transporter tout type de plats et de toutes tailles.", description:"Ce tutoriel est très facile à réaliser et ne vous prendre qu’une à deux heures de votre temps. A décliner en toutes les couleurs et toutes les matières, pour des compliments garantis ! ", instruction: "Étape par étape, ces instructions conviennent également aux débutants en couture.", time: 2)
  file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731932/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_photo_1_zkrnuo.jpg')
  sac_a_tartes.photos.attach(io: file1, filename: 'sac_a_tartes.jpg', content_type: 'image/jpg')
  file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731932/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_photo_2_qk76cl.jpg')
  sac_a_tartes.photos.attach(io: file2, filename: 'sac_a_tartes2.webp', content_type: 'image/webp')
  file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731932/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_photo_3_wvxuan.jpg')
  sac_a_tartes.photos.attach(io: file3, filename: 'sac_a_tartes3.jpg', content_type: 'image/jpg')
  file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731932/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_photo_4_gftqnt.jpg')
  sac_a_tartes.photos.attach(io: file4, filename: 'sac_a_tartes.jpg', content_type: 'image/jpg')
  file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731932/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_photo_5_sekr4l.jpg')
  sac_a_tartes.photos.attach(io: file5, filename: 'sac_a_tartes.jpg', content_type: 'image/jpg')
  notice1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731997/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_1_d5rgzb.png')
  sac_a_tartes.photos.attach(io: notice1, filename: 'sac_a_tartes_notice1.png', content_type: 'image/png')
  notice2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731997/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_2_i6taqg.png')
  sac_a_tartes.photos.attach(io: notice2, filename: 'sac_a_tartes_notice2.png', content_type: 'image/png')
  notice3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731997/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_3_xanaz2.png')
  sac_a_tartes.photos.attach(io: notice3, filename: 'sac_a_tartes_notice3.png', content_type: 'image/png')
  notice4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731997/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_4_y5kfq0.png')
  sac_a_tartes.photos.attach(io: notice4, filename: 'sac_a_tartes_notice4.png', content_type: 'image/png')
  notice5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731997/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_5_rf0miq.png')
  sac_a_tartes.photos.attach(io: notice5, filename: 'sac_a_tartes_notice5.png', content_type: 'image/png')
  notice6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731998/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_6_udc66f.png')
  sac_a_tartes.photos.attach(io: notice6, filename: 'sac_a_tartes_notice6.png', content_type: 'image/png')
  notice7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731998/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_7_hpsydb.png')
  sac_a_tartes.photos.attach(io: notice7, filename: 'sac_a_tartes_notice7.png', content_type: 'image/png')
  notice8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1655731998/FabricsApp/Sac%20%C3%A0%20tartes/sac_a_tartes_notice_Page_8_rgp7fi.png')
  sac_a_tartes.photos.attach(io: notice8, filename: 'sac_a_tartes_notice8.png', content_type: 'image/png')

  puts "#{Creation.count} creations created"
